# ARQUIVO: render.yaml (VERSÃO FINAL E CORRIGIDA)

services:
  # Serviço 1: Banco de Dados PostgreSQL (criado manualmente no painel)
  - type: psql
    name: sigaf-db
    postgres:
      majorVersion: 15
      port: 5432
    plan: free # Adicionando o plano aqui para consistência

  # Serviço 2: A Aplicação Web (Django)
  - type: web
    name: sigaf-web
    env: python
    plan: free
    
    # ALTERAÇÃO 1: Definindo a versão do Python da maneira correta
    pythonVersion: "3.11" 

    buildCommand: "./build.sh"
    startCommand: "gunicorn sigaf_project.wsgi:application"
    
    disks:
      - name: staticfiles
        mountPath: /opt/render/project/src/staticfiles
        sizeGB: 1
        
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sigaf_project.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          # ALTERAÇÃO 2: Simplificando a referência ao serviço de DB
          name: sigaf-db
          type: psql
          property: connectionString