# ARQUIVO: render.yaml (VERSÃO FINAL E CORRETA)

services:
  # O único serviço definido aqui é a nossa aplicação web
  - type: web
    name: sigaf-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sigaf_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sigaf_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SECRET_KEY
        generateValue: true
      # A variável DATABASE_URL será adicionada manualmente no painel do Render