# ARQUIVO: render.yaml (VERSÃO CORRIGIDA)

services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: psql  # <-- CORREÇÃO AQUI
    name: sigaf-db
    postgres:
      majorVersion: 15
      port: 5432

  # Serviço 2: A Aplicação Web (Django)
  - type: web
    name: sigaf-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sigaf_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sigaf_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9 # Ajuste para uma versão suportada pelo Render se necessário
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: psql  # <-- CORREÇÃO AQUI
          name: sigaf-db
          property: connectionString