# ARQUIVO: render.yaml (VERSÃO CORRIGIDA FINAL)

services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: db      # <-- CORREÇÃO FINAL
    name: sigaf-db
    # O bloco 'postgres' abaixo já diz ao Render que é um PostgreSQL
    postgres:
      majorVersion: 15
      port: 5432

  # Serviço 2: A Aplicação Web (Django)
  - type: web
    name: sigaf-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sigaf_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sigaf_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: db  # <-- CORREÇÃO FINAL
          name: sigaf-db
          property: connectionString