# Generated by Django 5.2.3 on 2025-07-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='codigo_ua',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Código UA'),
        ),
    ]
