# Generated by Django 5.2.3 on 2025-07-02 17:55

from django.db import migrations

# Lista completa de códigos de ocorrência baseada na especificação do projeto
CODIGOS = [
    {"codigo": "Livre", "denominacao": "Dia disponível para assinatura"},
    {"codigo": "SÁBADO", "denominacao": "Padrão para Sábados"},
    {"codigo": "DOMINGO", "denominacao": "Padrão para Domingos"},
    {"codigo": "002", "denominacao": "AFASTAMENTO POR LUTO"},
    {"codigo": "003", "denominacao": "AFASTAMENTO POR CASAMENTO"},
    {"codigo": "004", "denominacao": "AFASTAMENTO POR LEGISLAÇÃO SANITÁRIA"},
    {"codigo": "005", "denominacao": "AFASTAMENTO OBRIGATÓRIO POR LEI"},
    {"codigo": "006", "denominacao": "AFASTAMENTO PARA JURI"},
    {"codigo": "007", "denominacao": "AFASTAMENTO PARA SERVIÇO ELEITORAL"},
    {"codigo": "008", "denominacao": "AFASTAMENTO PARA CAMPANHA ELEITORAL"},
    {"codigo": "009", "denominacao": "AFASTAMENTO PARA DEPOIMENTO EM COMISSÃO DE INQUÉRITO"},
    {"codigo": "010", "denominacao": "DISPENSA DE PONTO"},
    {"codigo": "011", "denominacao": "FALTA ABONADA POR DOENÇA"},
    {"codigo": "012", "denominacao": "FÉRIAS DO EXERCÍCIO"},
    {"codigo": "013", "denominacao": "FÉRIAS EXERCÍCIOS ANTERIORES"},
    {"codigo": "014", "denominacao": "LICENÇA ESPECIAL A TÍTULO DE PRÊMIO"},
    {"codigo": "017", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - INICIAL SEM ALTA"},
    {"codigo": "018", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - INICIAL COM ALTA"},
    {"codigo": "019", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - PRORROGAÇÃO SEM ALTA"},
    {"codigo": "020", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - PRORROGAÇÃO COM ALTA"},
    {"codigo": "021", "denominacao": "LICENÇA ACIDENTE EM SERVIÇO"},
    {"codigo": "022", "denominacao": "LICENÇA DOENÇA PESSOA DA FAMÍLIA"},
    {"codigo": "023", "denominacao": "LICENÇA GESTANTE"},
    {"codigo": "025", "denominacao": "LICENÇA ALEITAMENTO"},
    {"codigo": "026", "denominacao": "SUSPENSÃO PREVENTIVA"},
    {"codigo": "029", "denominacao": "IMPONTUALIDADE"},
    {"codigo": "030", "denominacao": "FALTA"},
    {"codigo": "031", "denominacao": "ATRASO"},
    {"codigo": "035", "denominacao": "AFASTAMENTO PARA ESTUDOS"},
    {"codigo": "036", "denominacao": "AFASTAMENTO PARA MISSÃO OFICIAL"},
    {"codigo": "038", "denominacao": "LICENÇA MANDATO LEGIS / EXEC C/VENC"},
    {"codigo": "050", "denominacao": "PRISÃO 1/3"},
    {"codigo": "051", "denominacao": "PRISÃO 2/3"},
    {"codigo": "052", "denominacao": "SUSPENSÃO CONVERTIDA EM MULTA"},
    {"codigo": "054", "denominacao": "FALTA ABONADA PARA PROVA OU EXAME EM CONCURSO PÚBLICO"},
    {"codigo": "056", "denominacao": "AFASTAMENTO PARA ESTÁGIO EXPERIMENTAL"},
    {"codigo": "057", "denominacao": "SERVIDOR EM DISPONIBILIDADE"},
    {"codigo": "061", "denominacao": "FALTA POR GREVE"},
    {"codigo": "062", "denominacao": "SUSPENSÃO"},
    {"codigo": "065", "denominacao": "AFASTAMENTO POR ABANDONO DE CARGO"},
    {"codigo": "066", "denominacao": "LICENÇA MANDATO LEGIS / EXEC S/VENC"},
    {"codigo": "067", "denominacao": "LICENÇA PARA SERVIÇO MILITAR"},
    {"codigo": "069", "denominacao": "LICENÇA PARA ACOMPANHAR CÔNJUGE"},
    {"codigo": "070", "denominacao": "LICENÇA PARA TRATAR DE INTERESSE PARTICULAR"},
    {"codigo": "074", "denominacao": "BLOQUEIO PAGAMENTO - ACUMULAÇÃO ILÍCITA"},
    {"codigo": "075", "denominacao": "PEDIDO DE EXONERAÇÃO FORA DO EXERCÍCIO"},
    {"codigo": "094", "denominacao": "BLOQUEIO PAGAMENTO-ATENDER EXIGÊNCIA"},
    {"codigo": "100", "denominacao": "LICENÇA DOENÇA PROFISSIONAL"},
    {"codigo": "101", "denominacao": "AFASTAMENTO PARA DOAÇÃO DE SANGUE"},
    {"codigo": "102", "denominacao": "AFASTAMENTO PARA PROVA EM VESTIBULAR"},
    {"codigo": "103", "denominacao": "FALTA ABONADA PARA FINS DISCIPLINARES"},
    {"codigo": "104", "denominacao": "AFAST CURSO FORMAÇÃO ETAPA CONCURSO C/VENC"},
    {"codigo": "105", "denominacao": "AFAST CURSO FORMAÇÃO ETAPA CONCURSO S/ VENC"},
    {"codigo": "106", "denominacao": "LICENÇA ADOÇÃO"},
    {"codigo": "107", "denominacao": "LICENÇA ADOÇÃO - PAI"},
    {"codigo": "108", "denominacao": "AFASTAMENTO PARA EXAME PREVENTIVO"},
    {"codigo": "109", "denominacao": "AFASTAMENTO POR DETERMINAÇÃO JUDICIAL COM VENCIMENTO"},
    {"codigo": "110", "denominacao": "AFASTAMENTO POR DETERMINAÇÃO JUDICIAL SEM VENCIMENTO"},
    {"codigo": "111", "denominacao": "FALTA ABONADA CONTRATO TEMPORARIO"},
    {"codigo": "117", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE INICIAL - CLT"},
    {"codigo": "118", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE INICIAL - CONTR TEMP"},
    {"codigo": "120", "denominacao": "LICENÇA ACIDENTE TRABALHO INICIAL - INSS"},
    {"codigo": "121", "denominacao": "LICENÇA ACIDENTE TRABALHO - RGPS"},
    {"codigo": "124", "denominacao": "LICENÇA GESTANTE PRÉ-TERMO"},
    {"codigo": "150", "denominacao": "PRISÃO - ABSOLVIÇÃO AFINAL"},
    {"codigo": "153", "denominacao": "LICENÇA GESTANTE COMPLEMENTO LEI 128/09"},
    {"codigo": "156", "denominacao": "AFASTAMENTO PARA ESTÁGIO PROBATÓRIO"},
    {"codigo": "161", "denominacao": "FALTA POR GREVE ABONADA"},
    {"codigo": "162", "denominacao": "FALTA POR GREVE ABONADA COM REPOSIÇÃO"},
    {"codigo": "165", "denominacao": "ABANDONO SERVIÇO CONTRATO TEMPORARIO"},
    {"codigo": "200", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE (Militar)"},
    {"codigo": "201", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - ATO SERVIÇO (Militar)"},
    {"codigo": "202", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE -MOLÉSTIA INFECTO CONTAGIOSA (Militar)"},
    {"codigo": "203", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - DECLARADO INCAPAZ (Militar)"},
    {"codigo": "204", "denominacao": "LICENÇA TRATAMENTO DE SAÚDE - DECL INCAPAZ - ATO SERVIÇO (Militar)"},
    {"codigo": "208", "denominacao": "TRÂNSITO (Militar)"},
    {"codigo": "209", "denominacao": "INSTALAÇÃO (Militar)"},
    {"codigo": "210", "denominacao": "DISPENSA DE SERVIÇO (Militar)"},
    {"codigo": "211", "denominacao": "CONDENAÇÃO / PRISÃO (Militar)"},
    {"codigo": "212", "denominacao": "À DISPOSIÇÃO DA JUSTIÇA COMUM (Militar)"},
    {"codigo": "213", "denominacao": "AUSENTE (Militar)"},
    {"codigo": "214", "denominacao": "DESAPARECIDO (Militar)"},
    {"codigo": "215", "denominacao": "AGREGADO POR DESERÇÃO (Militar)"},
    {"codigo": "216", "denominacao": "AGREGADO POR EXTRAVIO (Militar)"},
    {"codigo": "217", "denominacao": "EM PROCESSO DE EXONERAÇÃO EX OFFICIO (Militar)"},
    {"codigo": "218", "denominacao": "LICENÇA PARA TRATAMENTO DE SAÚDE DETERMINAÇÃO JUDICIAL"},
    {"codigo": "300", "denominacao": "PRESENÇA"},
    {"codigo": "315", "denominacao": "LICENÇA MATERNIDADE DETERMINAÇÃO JUDICIAL"},
    {"codigo": "361", "denominacao": "ABONO FALTAS GREVE DET JUD"},
]

def popular_codigos(apps, schema_editor):
    CodigoOcorrencia = apps.get_model('core', 'CodigoOcorrencia')
    for codigo_data in CODIGOS:
        CodigoOcorrencia.objects.create(
            codigo=codigo_data["codigo"],
            denominacao=codigo_data["denominacao"]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_codigos),
    ]