# Generated by Django 5.2.3 on 2025-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unidade_codigo_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhaponto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
