# Generated by Django 5.2.3 on 2025-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhaponto',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='folhaponto',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre (Jan-Fev-Mar)'), (2, '2º Trimestre (Abr-Mai-Jun)'), (3, '3º Trimestre (Jul-Ago-Set)'), (4, 'º Trimestre (Out-Nov-Dez)')]),
        ),
    ]
