# Generated by Django 5.2.3 on 2025-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_folhaponto_ativa_alter_folhaponto_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhaponto',
            name='status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Arquivada', 'Arquivada')], default='Em Andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='folhaponto',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre (Jan-Fev-Mar)'), (2, '2º Trimestre (Abr-Mai-Jun)'), (3, '3º Trimestre (Jul-Ago-Set)'), (4, '4º Trimestre (Out-Nov-Dez)')]),
        ),
    ]
