# Generated by Django 5.2.3 on 2025-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_unidades_gerenciadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhaponto',
            name='cargo_servidor_na_folha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo na Época'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Assistente I', 'Assistente I'), ('Assistente II', 'Assistente II'), ('Auxiliar Policial de Necropsia', 'Auxiliar Policial de Necropsia'), ('Comissário de Polícia', 'Comissário de Polícia'), ('Inspetor de Polícia', 'Inspetor de Polícia'), ('Investigador Policial', 'Investigador Policial'), ('Oficial de Cartório Policial', 'Oficial de Cartório Policial'), ('Perito Criminal', 'Perito Criminal'), ('Perito Legista', 'Perito Legista'), ('Perito Papiloscopista', 'Perito Papiloscopista'), ('Piloto Policial', 'Piloto Policial'), ('Técnico Policial de Necropsia', 'Técnico Policial de Necropsia'), ('Delegado de Polícia', 'Delegado de Polícia'), ('Agente de Pessoal', 'Agente de Pessoal'), ('Administrador Geral', 'Administrador Geral')], default='Investigador Policial', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status_servidor',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Aposentado', 'Aposentado'), ('Demitido', 'Demitido'), ('Exonerado', 'Exonerado'), ('Licenciado', 'Licenciado'), ('Falecido', 'Falecido')], default='Ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidades_atuacao',
            field=models.ManyToManyField(blank=True, help_text='Selecione as unidades pelas quais este usuário pode ser responsável por gerência (Agente de Pessoal) ou conferência de folhas (Delegado de Polícia/Servidor-Conferente).', to='core.unidade', verbose_name='Unidades de Atuação (Gerência/Conferência)'),
        ),
    ]
