# Generated by Django 5.2.3 on 2026-03-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_folhaponto_cargo_servidor_na_folha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='regime_plantao',
            field=models.BooleanField(default=False, verbose_name='Regime de Plantão (Finais de Semana Livres)'),
        ),
    ]
