# Generated by Django 5.2.3 on 2026-03-20 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unidade_regime_plantao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Servidor', 'Servidor Comum'), ('Delegado de Polícia', 'Delegado de Polícia'), ('Agente de Pessoal', 'Agente de Pessoal'), ('Administrador Geral', 'Administrador Geral')], default='Servidor', max_length=50, verbose_name='Função no Sistema'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo', verbose_name='Cargo'),
        ),
    ]
