# Generated by Django 5.2.3 on 2025-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhaponto',
            name='motivo_status',
            field=models.CharField(blank=True, help_text='Campo para depuração do status.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidades_gerenciadas',
            field=models.ManyToManyField(blank=True, to='core.unidade', verbose_name='Unidades Gerenciadas'),
        ),
    ]
