# Generated by Django 5.2.3 on 2026-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cargo_alter_usuario_perfil_usuario_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoocorrencia',
            options={'ordering': ['codigo'], 'verbose_name': 'Código de Ocorrência', 'verbose_name_plural': 'Códigos de Ocorrência'},
        ),
        migrations.AddField(
            model_name='codigoocorrencia',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo no Sistema'),
        ),
        migrations.AlterField(
            model_name='codigoocorrencia',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigla/Código'),
        ),
        migrations.AlterField(
            model_name='codigoocorrencia',
            name='denominacao',
            field=models.CharField(max_length=255, verbose_name='Denominação'),
        ),
        migrations.AlterField(
            model_name='codigoocorrencia',
            name='descricao_completa',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
    ]
