# Generated by Django 5.2.3 on 2026-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_codigoocorrencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Precisa trocar a senha no próximo login?'),
        ),
    ]
